services:
  # app:
  #   build: .
  #   container_name: pakia_buckets
  #   ports:
  #     - "7072:7071"
  #   depends_on:
  #     - mariadb
  #     - mongodb
  #     - minio
  #     # - redis
  #     # - rabbitmq
  #   environment:
  #     SPRING_APPLICATION_NAME: Poetic-Justice
  #     SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/spring?allowPublicKeyRetrieval=true&useSSL=false
  #     SPRING_DATASOURCE_USERNAME: victoralvin
  #     SPRING_DATASOURCE_PASSWORD: HelloWorld20*
  #     SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/springboot
  #     SPRING_REDIS_HOST: redis
  #     SPRING_MINIO_ENDPOINT: http://minio:9000
  #     SPRING_MINIO_ACCESS_KEY: minioadmin
  #     SPRING_MINIO_SECRET_KEY: minioadmin
  #     SPRING_MINIO_BUCKET: 
  #   volumes:
  #     - app-data:/app/data

  mariadb:
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: spring
      MYSQL_USER: victoralvin
      MYSQL_PASSWORD: HelloWorld20*
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  # mongodb:
  #   image: mongo:latest
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb-data:/data/db
  # mysql:
  #   image: mysql:latest
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_DATABASE: spring
  #     MYSQL_USER: victoralvin
  #     MYSQL_PASSWORD: HelloWorld20*
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql-data:/var/lib/mysql

  # ORACLE DB
  oracle-db:
    image: gvenzl/oracle-free:latest
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=Egf2018
      - ORACLE_DATABASE=orcl
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./init-sql:/container-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/Egf2018@//localhost:1521/orcl", "select 1 from dual"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 120s
    restart: unless-stopped

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  # redis:
  #   image: redis:7-alpine
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"     # for backend communication
  #     - "15672:15672"   # for management UI
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
volumes:
  # app-data:
  mariadb-data:
  # mongodb-data:
  oracle-data:
  minio-data:
  # mysql-data:
  # redis-data: