spring.application.name=Poetic-Justice
spring.datasource.url=${DB_URL}
spring.data.mongodb.uri=${MONGO_URI}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

schedule.interval.seconds=${SCHEDULE_INTERVAL_SECONDS:60}
sms.process.interval.seconds=60
email.process.interval.seconds=60
dlq.retry.interval.seconds=3600

# Africa's Talking Credentials
SMS.AfricasTalking.Chamasoft.Username=your_username
SMS.AfricasTalking.Chamasoft.ApiKey=your_api_key
SMS.AfricasTalking.Chamasoft.senderId=your_sender_id

# Postmark Credentials
Email.Postmark.Chamasoft.ApiToken=your_postmark_api_token
Email.Postmark.Chamasoft.SenderEmail=sender@yourdomain.com
Email.Postmark.Chamasoft.MessageStream=notification

spring.jpa.hibernate.ddl-auto=update
spring.devtools.add-properties=false
logging.level.web=DEBUG
# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=${PORT}
server.error.include-exception=false
server.error.include-message=always

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.web.resources.static-locations=classpath:/static/,file:uploads/
logging.level.liquibase=DEBUG
file.upload-dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
logging.level.org.springframework.core.env=DEBUG