logging.level.liquibase=DEBUG
logging.level.web=DEBUG
logging.level.org.springframework.core.env=DEBUG

file.upload-dir=uploads

spring.application.name=Poetic-Justice
spring.datasource.url=${DB_URL}
spring.data.mongodb.uri=${MONGO_URI}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

schedule.interval.seconds=${SCHEDULE_INTERVAL_SECONDS:60}
sms.process.interval.seconds=60
email.process.interval.seconds=60
dlq.retry.interval.seconds=3600

# Africa's Talking Credentials
SMS.AfricasTalking.Chamasoft.Username=${SMS_AF_CHAMASOFT_USERNAME}
SMS.AfricasTalking.Chamasoft.ApiKey=${SMS_AF_CHAMASOFT_APIKEY}
SMS.AfricasTalking.Chamasoft.senderId=${SMS_AF_CHAMASOFT_SENDERID}

# Postmark Credentials
Email.Postmark.Chamasoft.ApiToken=${POSTMARK_CHAMASOFT_APITOKEN}
Email.Postmark.Chamasoft.SenderEmail=${POSTMARK_CHAMASOFT_SENDEREMAIL}
Email.Postmark.Chamasoft.MessageStream=${POSTMARK_CHAMASOFT_MESSAGESTREAM}

spring.jpa.hibernate.ddl-auto=update
spring.devtools.add-properties=false

# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=${PORT}
server.error.include-exception=false
server.error.include-message=always

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.rabbitmq.addresses=amqp://localhost:5672

spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

redis.host=localhost
redis.port=6379

# src/main/resources/application-dev.properties
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin

file.storage.path=uploads/