spring.profiles.active=dev

logging.level.liquibase=DEBUG
logging.level.web=DEBUG
logging.level.org.springframework.core.env=DEBUG

file.upload-dir=uploads

spring.application.name=Poetic-Justice
spring.datasource.url=${DB_URL}
spring.data.mongodb.uri=${MONGO_URI}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

schedule.interval.seconds=${SCHEDULE_INTERVAL_SECONDS:60}
sms.process.interval.seconds=60
email.process.interval.seconds=60
dlq.retry.interval.seconds=3600

spring.jpa.hibernate.ddl-auto=update
spring.devtools.add-properties=false

# spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
server.port=${PORT}
server.error.include-exception=false
server.error.include-message=always

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.rabbitmq.addresses=amqp://localhost:5672

spring.web.resources.static-locations=classpath:/static/,file:uploads/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=100MB

# Redis
spring.redis.jedis.host=localhost
spring.redis.jedis.port=6379
spring.redis.lettuce.host=localhost
spring.redis.lettuce.port=6379

# MinIO
minio.url=http://localhost:9000
minio.access-key=minioadmin
minio.secret-key=minioadmin
app.storage.public-bucket=publicuploader
app.storage.private-bucket=privateuploader
app.storage.endpoint=minio.example.com
app.storage.cleanup-ms=600000


file.storage.path=uploads/

# RabbitMQ
rabbitmq.queue.file-upload=file.upload.queue

app.rabbit.queues=file.upload.queue,file.process.queue

rabbitmq.retry.max-attempts=3

spring.rabbitmq.listener.simple.missing-queues-fatal=false
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.retry.multiplier=2.0